sudo: false

language:
  - python

python:
  - 3.8.5

install:
  - pip install -r requirements.txt
  - pip install pytest-cov codecov

script:
  - pytest --verbose --capture=no --cov=eiov_sorter

after_success:
  - codecov

notifications:
  email: false